// <auto-generated />
namespace HTML_form_generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PreMadeFormFree : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreMadeFormFree));
        
        string IMigrationMetadata.Id
        {
            get { return "202009302109145_PreMadeForm-Free"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
