// <auto-generated />
namespace HTML_form_generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PreMadeFormModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreMadeFormModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202008270026373_PreMadeFormModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
